/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface getToken {
  id: string;
  moduleName: string;
}

export interface login {
  email: string;
  password: string;
}

export interface register {
  birthDate: Date;
  email: string;
  id?: string;
  name: string;
  password: string;
  phone: string;
  surname: string;
}
