/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface getToken {
  query: {
    id: string;
  };
}

export interface login {
  body: {
    password: string;
    username: string;
  };
}

export interface register {
  body: {
    birthDate: Date;
    id?: string;
    name: string;
    password: string;
    phone: string;
    surname: string;
    username: string;
  };
}
