/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type email = string;

export type id = string;

export type phone = string;

export type socialSecurityNumber = string;
