/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface getUser {
  id: string;
}

export interface getUsers {
  ids?: string[];
}

export interface getUsersByName {
  string: string;
}

export interface user {
  email: string;
  id: string;
  name: string;
  permissions?: any;
  surname: string;
}
