/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface getUser {
  query: {
    id: string;
  };
}

export interface getUsers {
  query: {
    ids?: string[];
  };
}

export interface getUsersByName {
  query: {
    string: string;
  };
}

export interface user {
  id: string;
  name: string;
  permissions?: any;
  surname: string;
  username: string;
}
