/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface addPermission {
  body: {
    permissionPath: string[];
  };
  query: {
    id: string;
  };
}

export interface getPermission {
  query: {
    id: string;
  };
}

export interface getPermissions {
  query: {
    ids?: string[];
  };
}

export interface getToken {
  query: {
    id: string;
  };
}

export interface getUser {
  query: {
    id: string;
  };
}

export interface getUsers {
  query: {
    ids?: string[];
  };
}

export interface getUsersByName {
  query: {
    string: string;
  };
}

export interface login {
  body: {
    password: string;
    username: string;
  };
}

export interface register {
  body: {
    birthDate: Date;
    id?: string;
    name: string;
    password: string;
    phone: string;
    surname: string;
    username: string;
  };
}

export interface removePermission {
  body: {
    permissionPath: string[];
  };
  query: {
    id: string;
  };
}

export interface user {
  id: string;
  name: string;
  permissions: any;
  surname: string;
  username: string;
}
