/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface addPermission {
  id: string;
  permissionPath: string[];
}

export interface getPermission {
  id: string;
}

export interface getPermissions {
  ids: string[];
}

export interface getToken {
  id: string;
  moduleName: string;
}

export interface getUser {
  id: string;
}

export interface getUsers {
  ids?: string[];
}

export interface getUsersByName {
  string: string;
}

export interface login {
  email: string;
  password: string;
}

export interface register {
  birthDate: Date;
  email: string;
  id?: string;
  name: string;
  password: string;
  phone: string;
  surname: string;
}

export interface removePermission {
  id: string;
  permissionPath: string[];
}

export interface user {
  email: string;
  id: string;
  name: string;
  permissions: any;
  surname: string;
}
