/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface addPermission {
  id: string;
  permissionPath: string[];
}

export interface getPermission {
  id: string;
}

export interface getPermissions {
  ids: string[];
}

export interface removePermission {
  id: string;
  permissionPath: string[];
}
