/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface addPermission {
  body: {
    permissionPath: string[];
  };
  query: {
    id: string;
  };
}

export interface getPermission {
  query: {
    id: string;
  };
}

export interface getPermissions {
  query: {
    ids?: string[];
  };
}

export interface removePermission {
  body: {
    permissionPath: string[];
  };
  query: {
    id: string;
  };
}
