/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface middleware {
  body: object;
  headers: object;
  method: string;
  path: string;
  query: object;
}
