/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createSample {
  body: {
    age?: number;
    name: string;
  };
  query?: object;
}

export interface deleteSample {
  query: {
    name: string;
  };
}

export interface getSample {
  query: {
    name: string;
  };
}

export interface getSamples {
  query: {
    name?: string;
  };
}

export interface query {
  name: string;
}

export interface queryAll {
  name?: string;
}

export interface updateSample {
  body?: {
    age?: number;
    name?: string;
  };
  query?: {
    name: string;
  };
}
