/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface login {
  token: string;
}

export interface user {
  email: string;
  id: string;
  name: string;
  permissions: any;
  surname: string;
}
